In [2]:
import numpy as np

In [ ]:
ind_array = np.random.randint(1, 4, size=(2, 3))  # Ensure values are within bounds
data = np.array([[
    [1,1,1,1,1],
    [1,3,5,7,9],
    [100,0,0,0,0]
],
[
    [-1,1,1,2,58],
    [1,2,3,4,5],
    [0,1,2,3,4]
]
])

# proper way to broadcast freqdomain
freqdomain = np.array([0,5,10,15,20]) # freqdomain, i.e. results from fftfreq()
freqdomain = np.repeat(np.repeat(freqdomain[np.newaxis,:], 3, axis=0)[np.newaxis,:,:], 2, axis=0) # freqdomain put in every entry of a (M, N) array, so resulting shape is (M, N, len(freqdomain))

# Gives correct slices
slices = ind_array[:,:,np.newaxis] + np.arange(-1,2)[np.newaxis, np.newaxis, :]

# Check the results
freqdomain_sliced = np.take_along_axis(freqdomain, slices, axis=2)
print('Indices')
print(ind_array)
print('')
# print('freqdomain_slices')
# print(freqdomain_sliced)
# print('')



new_data2 = np.take_along_axis(data, slices, axis=2)
new_data2_sum = np.sum(new_data2, axis=2)
weights = new_data2/np.sum(new_data2, axis=2)[:,:,np.newaxis]
print('new_data2')
print(new_data2)
print('')
print('new_data2_sum')
print(new_data2_sum)

print(new_data2/new_data2_sum[:,:,np.newaxis])


# Prepare arrays to extract values from data array
# # Use np.arange to create the first two dimensions of indices
# new_data = data[np.arange(2)[:, None], np.arange(500), ind_array[:, :, None] + indices]

# # Check the resulting shape and a small portion of new_data
# print("Shape of new_data:", new_data.shape)  # Should be (2, 500, 7)
# print("Sample of new_data:", new_data[:, :5, :])  # Display first 5 elements

Indices
[[2 2 1]
 [2 3 3]]

new_data2
[[[  1   1   1]
  [  3   5   7]
  [100   0   0]]

 [[  1   1   2]
  [  3   4   5]
  [  2   3   4]]]

new_data2_sum
[[  3  15 100]
 [  4  12   9]]
[[[0.33333333 0.33333333 0.33333333]
  [0.2        0.33333333 0.46666667]
  [1.         0.         0.        ]]

 [[0.25       0.25       0.5       ]
  [0.25       0.33333333 0.41666667]
  [0.22222222 0.33333333 0.44444444]]]
